### ISSUE TITLE
Define colors as globals at the top of the script

### ISSUE THREAD

**Issue by elainajones** [elainajones/remarkable-calendar#3]
Move color definitions to global variables at the top of the script for easy modification. This makes it easier for user so to further customize for their needs and organizes the color grouping better.

**Comment by kevinzl13** [comment]
Sure, I can do it.

**Comment by elainajones** [comment]
@kevinzl13 Thanks for your willingness to contribute to this issue. Unfortunately, I'll be accepting my changes from #6 instead. I generally open issues to track my own work and resolve these fairly quickly but new ideas are always welcome.

I'll be happy to review any future pull from you in the future. You may consider assisting with #7 instead.

**Comment by elainajones** [comment]
Closing with completion of pull request #6 for moving color definitions to the top of the file.
